name: eventistan
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text:
  cached_network_image: ^3.2.1
  collection:
  csv:
  dropdown_button2:
  expandable:
  file_picker:
  firebase_auth:
  firebase_core:
  firebase_performance:
  firebase_storage:
  flutter_animate:
  flutter_cache_manager:
  flutter_plugin_android_lifecycle:
  flutter_rating_bar:
  flutter_secure_storage:
  font_awesome_flutter:
  from_css_color:
  go_router:
  google_fonts:
  google_sign_in:
  image_picker:
  intl:
  json_path:
  mime_type:
  page_transition:
  path_provider:
  plugin_platform_interface:
  provider:
  rxdart:
  shared_preferences:
  sign_in_with_apple: 4.3.0
  sqflite: 2.2.6
  stream_transform: 2.1.0
  synchronized: 3.1.0
  text_search: 1.0.1
  timeago: 3.2.2
  url_launcher:
  video_player: 2.8.1
  flutter_riverpod:
  dio:
  fluttertoast:
  cupertino_icons: ^1.0.0
  flutter_stripe: ^10.1.1
  google_maps_flutter: ^2.7.0
  location: ^6.0.2
  flutter_polyline_points: ^2.0.0
  geolocator: ^12.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0
  change_app_package_name: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/